# Generated by Django 3.1.3 on 2022-06-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('money', models.IntegerField(default=200)),
                ('money_spent_today', models.IntegerField(default=0)),
                ('money_spent_this_month', models.IntegerField(default=0)),
                ('money_spent_this_year', models.IntegerField(default=0)),
            ],
        ),
    ]
