# Generated by Django 4.1.1 on 2022-11-07 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_item_time_it_was_bought_standingorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='standingorder',
            name='type',
            field=models.CharField(choices=[('IMPORTANT', 'Important'), ('LESS IMPORTANT', 'Less Important'), ('NOT IMPORTANT', 'Not Important')], default='IMPORTANT', max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='time_it_was_bought',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 13, 17, 16, 767328)),
        ),
    ]
