# Generated by Django 3.1.3 on 2022-06-06 18:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='time_it_was_bought',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 6, 18, 10, 39, 678940, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
