# Generated by Django 4.1.1 on 2022-11-07 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_standingorder_type_alter_item_time_it_was_bought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standingorder',
            name='duration',
        ),
        migrations.AlterField(
            model_name='item',
            name='time_it_was_bought',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 14, 0, 28, 819057)),
        ),
    ]
