# Generated by Django 4.1.1 on 2022-11-11 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_item_time_it_was_bought_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='expenses',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='monthly_income',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='time_it_was_bought',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 11, 10, 8, 51, 210227)),
        ),
    ]
