# Generated by Django 4.1.1 on 2022-11-11 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_bio_profile_expenses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='expenses',
        ),
        migrations.AlterField(
            model_name='item',
            name='time_it_was_bought',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 11, 20, 22, 58, 875784)),
        ),
    ]
