# Generated by Django 4.1.1 on 2022-12-03 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_item_time_it_was_bought_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time_it_was_bought',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 20, 9, 51, 210061)),
        ),
    ]
