# Generated by Django 3.1.3 on 2022-06-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
