# Generated by Django 3.1.3 on 2022-06-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseproject', '0002_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
