# Generated by Django 3.1.3 on 2022-06-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseproject', '0004_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
